"""empty message

Revision ID: 120f5723396b
Revises: 71d625bc1ba5
Create Date: 2023-01-20 13:15:30.789659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120f5723396b'
down_revision = '71d625bc1ba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('dump', sa.Column('exchange_trade_id', sa.String(length=255), nullable=True))
    op.add_column('transaction', sa.Column('product_description', sa.String(length=255), nullable=False))
    op.add_column('transaction', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('transaction', sa.Column('shop_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transaction', 'shop', ['shop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'shop_id')
    op.drop_column('transaction', 'product_id')
    op.drop_column('transaction', 'product_description')
    op.drop_column('dump', 'exchange_trade_id')
    op.drop_table('shop')
    # ### end Alembic commands ###
