"""empty message

Revision ID: 14192a61b91c
Revises: e67407dfd7b5
Create Date: 2023-01-20 13:30:57.151922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14192a61b91c'
down_revision = 'e67407dfd7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('expiry_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'expiry_at')
    # ### end Alembic commands ###
