"""empty message

Revision ID: 1b6eb5a097f2
Revises: c17ef599aadd
Create Date: 2023-01-12 14:18:24.450191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b6eb5a097f2'
down_revision = 'c17ef599aadd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit', sa.Column('real_amount_received', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deposit', 'real_amount_received')
    # ### end Alembic commands ###
