"""empty message

Revision ID: 34545e53bae3
Revises: 7abc49305e5b
Create Date: 2023-01-11 17:11:36.581245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34545e53bae3'
down_revision = '7abc49305e5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('exchange_eur_pair_ticker', sa.String(length=255), nullable=False),
    sa.Column('exchange_usd_pair_ticker', sa.String(length=255), nullable=False),
    sa.Column('exchange_btc_pair_ticker', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('network',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('txn_hash', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('fiat_currency', sa.String(length=255), nullable=False),
    sa.Column('fiat_amount', sa.Integer(), nullable=False),
    sa.Column('deposit_address', sa.String(length=255), nullable=False),
    sa.Column('blockchain_txid', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('txn_hash')
    )
    op.create_table('coin_network',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=True),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coin_id'], ['coin.id'], ),
    sa.ForeignKeyConstraint(['network_id'], ['network.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('deposit', sa.Column('amount', sa.Integer(), nullable=False))
    op.add_column('deposit', sa.Column('coin_id', sa.Integer(), nullable=True))
    op.add_column('deposit', sa.Column('network_id', sa.Integer(), nullable=True))
    op.add_column('deposit', sa.Column('transaction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'deposit', 'coin', ['coin_id'], ['id'])
    op.create_foreign_key(None, 'deposit', 'transaction', ['transaction_id'], ['id'])
    op.create_foreign_key(None, 'deposit', 'network', ['network_id'], ['id'])
    op.drop_column('deposit', 'count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit', sa.Column('count', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'deposit', type_='foreignkey')
    op.drop_constraint(None, 'deposit', type_='foreignkey')
    op.drop_constraint(None, 'deposit', type_='foreignkey')
    op.drop_column('deposit', 'transaction_id')
    op.drop_column('deposit', 'network_id')
    op.drop_column('deposit', 'coin_id')
    op.drop_column('deposit', 'amount')
    op.drop_table('coin_network')
    op.drop_table('transaction')
    op.drop_table('network')
    op.drop_table('coin')
    # ### end Alembic commands ###
