"""empty message

Revision ID: 3dbea82573d4
Revises: cfcd9e6ff898
Create Date: 2023-01-11 18:56:54.661904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dbea82573d4'
down_revision = 'cfcd9e6ff898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kraken', sa.Column('secret', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kraken', 'secret')
    # ### end Alembic commands ###
