"""empty message

Revision ID: 67b58321149b
Revises: 84bd6fa1cdec
Create Date: 2023-01-20 13:27:40.310078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b58321149b'
down_revision = '84bd6fa1cdec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('expiry_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'expiry_at')
    # ### end Alembic commands ###
