"""empty message

Revision ID: 698d670510cb
Revises: a804ed62d625
Create Date: 2023-02-24 17:21:02.437277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698d670510cb'
down_revision = 'a804ed62d625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('real_fiat_received', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'real_fiat_received')
    # ### end Alembic commands ###
