"""empty message

Revision ID: 6c9e17650eb9
Revises: d59db8f0c25a
Create Date: 2023-01-11 17:35:48.896049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c9e17650eb9'
down_revision = 'd59db8f0c25a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit', sa.Column('blockchain_txid', sa.String(length=255), nullable=True))
    op.add_column('deposit', sa.Column('deposit_address', sa.String(length=255), nullable=True))
    op.drop_column('transaction', 'deposit_address')
    op.drop_column('transaction', 'blockchain_txid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('blockchain_txid', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('transaction', sa.Column('deposit_address', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('deposit', 'deposit_address')
    op.drop_column('deposit', 'blockchain_txid')
    # ### end Alembic commands ###
