"""empty message

Revision ID: 7d2ac2af4850
Revises: 6c9e17650eb9
Create Date: 2023-01-11 17:39:39.394004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d2ac2af4850'
down_revision = '6c9e17650eb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('deposit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transaction', 'deposit', ['deposit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'deposit_id')
    # ### end Alembic commands ###
