"""empty message

Revision ID: 9e8cef5b3ea1
Revises: 7d2ac2af4850
Create Date: 2023-01-11 17:51:31.713422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e8cef5b3ea1'
down_revision = '7d2ac2af4850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('deposit_ibfk_2', 'deposit', type_='foreignkey')
    op.drop_column('deposit', 'transaction_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit', sa.Column('transaction_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('deposit_ibfk_2', 'deposit', 'transaction', ['transaction_id'], ['id'])
    # ### end Alembic commands ###
