"""empty message

Revision ID: c17ef599aadd
Revises: 3dbea82573d4
Create Date: 2023-01-12 14:09:33.681924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c17ef599aadd'
down_revision = '3dbea82573d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit', sa.Column('real_amount_received', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deposit', 'real_amount_received')
    # ### end Alembic commands ###
