"""empty message

Revision ID: cfcd9e6ff898
Revises: 9e8cef5b3ea1
Create Date: 2023-01-11 18:41:50.638071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfcd9e6ff898'
down_revision = '9e8cef5b3ea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kraken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('coin', sa.Column('exchange_coin_ticker', sa.String(length=255), nullable=False))
    op.add_column('deposit', sa.Column('amount_timestamp', sa.DateTime(), nullable=True))
    op.add_column('network', sa.Column('exchange_network_ticker', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('network', 'exchange_network_ticker')
    op.drop_column('deposit', 'amount_timestamp')
    op.drop_column('coin', 'exchange_coin_ticker')
    op.drop_table('kraken')
    # ### end Alembic commands ###
