"""empty message

Revision ID: d59db8f0c25a
Revises: ce363f12e2ee
Create Date: 2023-01-11 17:33:11.815525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd59db8f0c25a'
down_revision = 'ce363f12e2ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deposit', 'amount',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('transaction', sa.Column('hash', sa.String(length=255), nullable=False))
    op.drop_index('txn_hash', table_name='transaction')
    op.create_unique_constraint(None, 'transaction', ['hash'])
    op.drop_column('transaction', 'txn_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('txn_hash', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'transaction', type_='unique')
    op.create_index('txn_hash', 'transaction', ['txn_hash'], unique=True)
    op.drop_column('transaction', 'hash')
    op.alter_column('deposit', 'amount',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
