"""empty message

Revision ID: e67407dfd7b5
Revises: 67b58321149b
Create Date: 2023-01-20 13:29:47.876506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e67407dfd7b5'
down_revision = '67b58321149b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('expiry_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'expiry_at')
    # ### end Alembic commands ###
